### ISSUE TITLE
Lib crashing the application

### ISSUE THREAD

**Issue by arkaisho** [hugobrancowb/barcode_bill_scanner#8]
I'm using this lib in one project but it has started to crash the app after fouding a barcode.
Environment informations:
Phone android version: android 8.0
Phone Model: Xiaomi redmi 5 plus
Flutter 3.3.6 

the application throws this Stack trace:
`
E/AndroidRuntime(19712): FATAL EXCEPTION: main
E/AndroidRuntime(19712): Process: br.com.zrobank.app, PID: 19712
E/AndroidRuntime(19712): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/barcode/Barcode;
E/AndroidRuntime(19712):     at com.google_barcode_kit.vision.BarcodeDetector$2.onSuccess(BarcodeDetector.java:87)
E/AndroidRuntime(19712):     at com.google_barcode_kit.vision.BarcodeDetector$2.onSuccess(BarcodeDetector.java:83)
E/AndroidRuntime(19712):     at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/AndroidRuntime(19712):     at android.os.Handler.handleCallback(Handler.java:794)
E/AndroidRuntime(19712):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19712):     at android.os.Looper.loop(Looper.java:176)
E/AndroidRuntime(19712):     at android.app.ActivityThread.main(ActivityThread.java:6651)
E/AndroidRuntime(19712):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19712):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
`
And the phone gives this problem description:
![image](https://user-images.githubusercontent.com/38983117/199782634-db4f25da-d39e-4ac5-9bac-b094047756f6.png)

**Comment by arkaisho** [comment]
I have discovered that the described error only happens when the lib is used with  https://pub.dev/packages/persona_flutter/versions/3.0.1-beta.0
